import { CP_ACCENT, CP_ACCENT_06, FONT_SANS } from "./styles";
import { Z } from "../data/constants";

// ── Homepage-specific styles ─────────────────────────────────────────────────
export const HP = {
  // Hero — split layout
  hero: {
    minHeight: "100dvh",
    display: "grid",
    gridTemplateColumns: "5fr 7fr",
    alignItems: "center",
    gap: 40,
    padding: "100px 48px 48px",
    position: "relative",
    background: "var(--cp-bg)",
    maxWidth: 1200,
    margin: "0 auto",
  },
  heroGlow: {
    position: "absolute",
    width: 600,
    height: 300,
    background: `radial-gradient(ellipse, ${CP_ACCENT_06} 0%, transparent 70%)`,
    pointerEvents: "none",
    top: "40%",
    left: "25%",
    transform: "translate(-50%, -50%)",
  },
  nav: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    display: "flex",
    alignItems: "center",
    padding: "16px 32px",
    zIndex: Z.MINI_HEADER,
    background: "var(--cp-mini-bg)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    borderBottom: "1px solid var(--cp-border-light)",
  },
  navBrand: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  // No entrance animation on the hero columns: they hold the LCP element (the
  // h1), and an opacity fade-in held LCP back until it finished (~0.8s). It
  // would also replay when React swaps in for the prerendered markup.
  heroLeft: {
    position: "relative",
    zIndex: 1,
  },
  heroRight: {
    position: "relative",
    zIndex: 1,
  },
  heroHeadline: {
    fontFamily: FONT_SANS,
    fontSize: 48,
    fontWeight: 700,
    letterSpacing: "-0.03em",
    lineHeight: 1.1,
    color: "var(--cp-text)",
    marginBottom: 20,
  },
  heroSub: {
    fontFamily: FONT_SANS,
    fontSize: 18,
    fontWeight: 300,
    lineHeight: 1.7,
    color: "var(--cp-text-muted)",
    marginBottom: 28,
    maxWidth: 440,
  },
  heroPrimary: {
    display: "inline-flex",
    alignItems: "center",
    padding: "14px 32px",
    border: "none",
    borderRadius: 6,
    background: CP_ACCENT,
    color: "#fff",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: FONT_SANS,
    letterSpacing: -0.2,
  },
  heroProblem: {
    display: "block",
    fontFamily: FONT_SANS,
    lineHeight: 1.4,
    fontSize: 14,
    fontWeight: 500,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: CP_ACCENT,
    marginBottom: 12,
  },
  heroTrust: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px 18px",
    listStyle: "none",
    padding: 0,
    margin: "20px 0 0",
    fontSize: 13,
    color: "var(--cp-text-secondary)",
    fontWeight: 500,
    letterSpacing: "0.01em",
  },
  heroTrustItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    color: "var(--cp-text-secondary)",
  },
  // "What you get" preview: a messy line and the quote card it becomes
  heroPreview: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 10,
    marginTop: 32,
    maxWidth: 440,
  },
  heroPreviewRaw: {
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: 13,
    color: "var(--cp-text-muted)",
    background: "var(--cp-bg-tab)",
    borderRadius: 4,
    padding: "7px 12px",
  },
  heroPreviewArrow: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    paddingLeft: 12,
    fontSize: 12,
    letterSpacing: "0.01em",
    color: "var(--cp-text-faint)",
  },
  heroPreviewCard: {
    alignSelf: "stretch",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: "14px 16px",
    background: "var(--cp-bg-card)",
    border: "1px solid var(--cp-border)",
    borderRadius: 6,
    boxShadow: "var(--cp-shadow-card)",
    textAlign: "left",
  },
  heroPreviewQuote: {
    fontSize: 16,
    lineHeight: 1.45,
    color: "var(--cp-text)",
  },
  heroPreviewMeta: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 13,
  },
  heroFinePrint: {
    display: "flex",
    gap: 8,
    fontSize: 12,
    lineHeight: 1.6,
    color: "var(--cp-text-muted)",
    maxWidth: 520,
    marginTop: 14,
  },

  // Sections
  section: {
    padding: "80px 48px",
  },
  sectionAlt: {
    background: "var(--cp-bg-panel)",
  },
  sectionInner: {
    maxWidth: 1100,
    margin: "0 auto",
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    color: CP_ACCENT,
    marginBottom: 12,
    fontFamily: FONT_SANS,
  },
  sectionHeadline: {
    fontFamily: FONT_SANS,
    fontSize: 32,
    fontWeight: 700,
    letterSpacing: "-0.03em",
    lineHeight: 1.2,
    color: "var(--cp-text)",
    marginBottom: 12,
  },
  sectionSub: {
    fontSize: 16,
    fontWeight: 300,
    lineHeight: 1.7,
    color: "var(--cp-text-muted)",
    maxWidth: 520,
    fontFamily: FONT_SANS,
  },

  // How it works — asymmetric split (text left, animation right)
  howSplit: {
    display: "grid",
    gridTemplateColumns: "5fr 7fr",
    gap: 48,
    alignItems: "center",
  },
  howLeft: {
    display: "flex",
    flexDirection: "column",
  },
  howRight: {
    maxWidth: 560,
  },

  // FAQ — native <details>/<summary> accordion
  faqList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  faqItem: {
    background: "var(--cp-bg-card)",
    border: "1px solid var(--cp-border-light)",
    borderRadius: 6,
    padding: "4px 18px",
  },
  faqQuestion: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "14px 0",
    cursor: "pointer",
    listStyle: "none",
    fontFamily: FONT_SANS,
    fontSize: 15,
    fontWeight: 600,
    color: "var(--cp-text)",
  },
  faqChevron: {
    flexShrink: 0,
    color: "var(--cp-text-faint)",
    transition: "transform .2s ease",
  },
  faqAnswer: {
    margin: "-4px 0 16px",
    fontFamily: FONT_SANS,
    fontSize: 14,
    lineHeight: 1.65,
    color: "var(--cp-text-muted)",
    maxWidth: "65ch",
  },

  // Features — heading left, 2×2 grid split by hairlines right
  featuresSplit: {
    display: "grid",
    gridTemplateColumns: "340px minmax(0, 1fr)",
    columnGap: 64,
    rowGap: 32,
    alignItems: "start",
  },
  featuresGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    borderTop: "1px solid var(--cp-border)",
  },
  feature: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    minWidth: 0,
  },
  featureLeft: {
    padding: "26px 28px 28px 0",
    borderRight: "1px solid var(--cp-border)",
  },
  featureRight: {
    padding: "26px 0 28px 28px",
  },
  featureTopRow: {
    borderBottom: "1px solid var(--cp-border)",
  },
  featureTitle: {
    fontFamily: FONT_SANS,
    fontSize: 16,
    fontWeight: 700,
    letterSpacing: "-0.01em",
    color: "var(--cp-text)",
  },
  featureDesc: {
    fontSize: 14,
    lineHeight: 1.6,
    color: "var(--cp-text-secondary)",
    fontFamily: FONT_SANS,
  },
  featureDemo: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
    marginTop: 6,
    fontSize: 12,
    color: "var(--cp-text-muted)",
  },
  featureChip: {
    fontSize: 11,
    padding: "1px 6px",
    border: "1px solid var(--cp-border)",
    borderRadius: 4,
    background: "var(--cp-bg-card)",
    color: "var(--cp-text-muted)",
  },
};

// ── Reveal transition helper ─────────────────────────────────────────────────
export const reveal = (visible, delay = 0) => ({
  opacity: visible ? 1 : 0,
  transform: visible ? "translateY(0)" : "translateY(40px)",
  transition: `opacity 0.8s ease ${delay}s, transform 0.8s ease ${delay}s`,
});
