import { CP_ACCENT, CP_ACCENT_06, FONT_SANS, FONT_SERIF } from "./styles";

// ── Timeline data ────────────────────────────────────────────────────────────
const TAG_COLORS = {
  Film:   { bg: "rgba(139,92,246,0.08)",  text: "#7A48CE" },
  Speech: { bg: "rgba(59,130,246,0.08)",  text: "#3967CD" },
  Person: { bg: "rgba(168,85,247,0.08)",  text: "#8B43CC" },
  Book:   { bg: "rgba(217,119,6,0.08)",   text: "#C07621" },
};

export const TIMELINE_MOMENTS = [
  {
    period: "First session",
    count: 5,
    quotes: [
      { text: "You can\u2019t handle the truth", source: "A Few Good Men", tag: "Film" },
      { text: "Be the change", source: "Gandhi", tag: "Speech" },
    ],
  },
  {
    period: "One week in",
    count: 23,
    quotes: [
      { text: "Less is more", source: "Mies van der Rohe", tag: "Person" },
      { text: "The only way out is through", source: "Robert Frost", tag: "Book" },
    ],
  },
  {
    period: "One month later",
    count: 87,
    quotes: [
      { text: "Cogito ergo sum", source: "Descartes", tag: "Person" },
      { text: "Stay hungry, stay foolish", source: "Steve Jobs", tag: "Speech" },
    ],
  },
];

// ── Homepage-specific styles ─────────────────────────────────────────────────
export const HP = {
  // Hero — split layout
  hero: {
    minHeight: "100vh",
    display: "grid",
    gridTemplateColumns: "5fr 7fr",
    alignItems: "center",
    gap: 40,
    padding: "100px 48px 48px",
    position: "relative",
    background: "var(--cp-bg)",
    maxWidth: 1200,
    margin: "0 auto",
  },
  heroGlow: {
    position: "absolute",
    width: 600,
    height: 300,
    background: `radial-gradient(ellipse, ${CP_ACCENT_06} 0%, transparent 70%)`,
    pointerEvents: "none",
    top: "40%",
    left: "25%",
    transform: "translate(-50%, -50%)",
  },
  nav: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    display: "flex",
    alignItems: "center",
    padding: "16px 32px",
    zIndex: 100,
    background: "var(--cp-mini-bg)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    borderBottom: "1px solid var(--cp-border-light)",
  },
  navBrand: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  navName: {
    fontFamily: FONT_SERIF,
    fontSize: 18,
    fontWeight: 700,
    letterSpacing: -0.5,
    color: "var(--cp-text)",
  },
  heroLeft: {
    animation: "fadeUp .8s ease",
    position: "relative",
    zIndex: 1,
  },
  heroRight: {
    animation: "fadeUp .8s .15s ease both",
    position: "relative",
    zIndex: 1,
  },
  heroHeadline: {
    fontFamily: FONT_SANS,
    fontSize: 48,
    fontWeight: 700,
    letterSpacing: "-0.03em",
    lineHeight: 1.1,
    color: "var(--cp-text)",
    marginBottom: 20,
  },
  heroSub: {
    fontFamily: FONT_SANS,
    fontSize: 18,
    fontWeight: 300,
    lineHeight: 1.7,
    color: "var(--cp-text-muted)",
    marginBottom: 28,
    maxWidth: 440,
  },
  heroPrimary: {
    display: "inline-flex",
    alignItems: "center",
    padding: "14px 32px",
    border: "none",
    borderRadius: 6,
    background: CP_ACCENT,
    color: "#fff",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: FONT_SANS,
    letterSpacing: -0.2,
  },
  heroProblem: {
    fontFamily: FONT_SANS,
    fontSize: 14,
    fontWeight: 500,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: CP_ACCENT,
    marginBottom: 12,
  },
  heroMiniDemo: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: "12px 16px",
    background: "var(--cp-bg-panel)",
    border: "1px solid var(--cp-border-light)",
    borderRadius: 6,
    marginTop: 4,
    marginBottom: 4,
  },
  miniDemoLabel: {
    fontSize: 10,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    color: "var(--cp-text-faint)",
  },
  miniDemoRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 13,
    flexWrap: "wrap",
  },
  miniDemoBefore: {
    color: "var(--cp-text-muted)",
    fontFamily: "'SF Mono','DM Mono',Menlo,monospace",
    fontSize: 12,
  },
  miniDemoAfter: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontWeight: 500,
    color: "var(--cp-text-secondary)",
  },
  miniDemoTag: {
    fontSize: 9,
    fontWeight: 700,
    padding: "2px 6px",
    borderRadius: 3,
    background: "rgba(59,130,246,0.08)",
    color: "#3967CD",
    letterSpacing: 0.3,
    textTransform: "uppercase",
    fontFamily: "'DM Mono',monospace",
  },
  heroTrust: {
    fontSize: 13,
    color: CP_ACCENT,
    fontWeight: 500,
    letterSpacing: 0.02,
    marginTop: 20,
  },

  // Sections
  section: {
    padding: "80px 48px",
  },
  sectionAlt: {
    background: "var(--cp-bg-panel)",
  },
  sectionInner: {
    maxWidth: 1100,
    margin: "0 auto",
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    color: CP_ACCENT,
    marginBottom: 12,
    fontFamily: FONT_SANS,
  },
  sectionHeadline: {
    fontFamily: FONT_SANS,
    fontSize: 32,
    fontWeight: 700,
    letterSpacing: "-0.03em",
    lineHeight: 1.2,
    color: "var(--cp-text)",
    marginBottom: 12,
  },
  sectionSub: {
    fontSize: 16,
    fontWeight: 300,
    lineHeight: 1.7,
    color: "var(--cp-text-muted)",
    maxWidth: 520,
    fontFamily: FONT_SANS,
  },

  // How it works — asymmetric split (text left, animation right)
  howSplit: {
    display: "grid",
    gridTemplateColumns: "5fr 7fr",
    gap: 48,
    alignItems: "center",
  },
  howLeft: {
    display: "flex",
    flexDirection: "column",
  },
  howRight: {
    maxWidth: 560,
  },

  // Timeline — horizontal
  timeline: {
    position: "relative",
    marginTop: 48,
    textAlign: "left",
  },
  timelineTrack: {
    position: "absolute",
    top: 4,
    left: 0,
    right: 0,
    height: 2,
    background: "var(--cp-border)",
    borderRadius: 1,
  },
  timelineTrackFill: {
    position: "absolute",
    top: 4,
    left: 0,
    width: "75%",
    height: 2,
    background: `linear-gradient(90deg, var(--cp-border-dim) 0%, ${CP_ACCENT} 100%)`,
    borderRadius: 1,
  },
  timelineColumns: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 24,
    position: "relative",
  },
  timelineMoment: {
    display: "flex",
    flexDirection: "column",
    paddingTop: 24,
    position: "relative",
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: "50%",
    background: "var(--cp-border-dim)",
    border: "2px solid var(--cp-bg-panel)",
    position: "absolute",
    top: -1,
    left: 0,
    zIndex: 1,
  },
  timelinePeriod: {
    fontSize: 11,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: 1,
    color: CP_ACCENT,
    marginBottom: 2,
    fontFamily: FONT_SANS,
  },
  timelineCount: {
    fontFamily: FONT_SANS,
    fontSize: 20,
    fontWeight: 700,
    color: "var(--cp-text)",
    marginBottom: 12,
  },
  timelineQuotes: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  timelineQuoteTag: (tag) => ({
    fontSize: 9,
    fontWeight: 700,
    padding: "2px 6px",
    borderRadius: 3,
    background: TAG_COLORS[tag]?.bg || "#F1F1EF",
    color: TAG_COLORS[tag]?.text || "#787774",
    letterSpacing: 0.3,
    textTransform: "uppercase",
    whiteSpace: "nowrap",
    flexShrink: 0,
    fontFamily: "'DM Mono',monospace",
  }),
  timelineQuote: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    background: "var(--cp-bg-card)",
    borderRadius: 6,
    border: "1px solid var(--cp-border-light)",
    fontSize: 12,
  },
  timelineQuoteText: {
    color: "var(--cp-text-secondary)",
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontFamily: FONT_SANS,
  },
  timelineQuoteSrc: {
    color: "var(--cp-text-muted)",
    fontSize: 11,
    whiteSpace: "nowrap",
    flexShrink: 0,
    fontFamily: FONT_SANS,
  },

  // Features — single row of 4 cards
  featuresGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 16,
    marginTop: 40,
    textAlign: "left",
  },
  featureCard: {
    background: "var(--cp-bg-card)",
    border: "1px solid var(--cp-border-light)",
    borderRadius: 6,
    padding: "20px 18px",
    boxShadow: "0 1px 4px rgba(0,0,0,0.04)",
  },
  featureIconWrap: {
    width: 38,
    height: 38,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
    marginBottom: 14,
  },
  featureTitle: {
    fontFamily: FONT_SANS,
    fontSize: 14,
    fontWeight: 600,
    color: "var(--cp-text)",
    marginBottom: 6,
  },
  featureDesc: {
    fontSize: 13,
    fontWeight: 300,
    lineHeight: 1.5,
    color: "var(--cp-text-muted)",
    fontFamily: FONT_SANS,
  },
};

// ── Reveal transition helper ─────────────────────────────────────────────────
export const reveal = (visible, delay = 0) => ({
  opacity: visible ? 1 : 0,
  transform: visible ? "translateY(0)" : "translateY(40px)",
  transition: `opacity 0.8s ease ${delay}s, transform 0.8s ease ${delay}s`,
});
