// Shared-collection lookups used by /api/share (JSON), /api/share-page (the
// server-rendered /c/:id page shell) and /api/og (the share card image).

// Public share IDs are generated by share.js as 8 chars of [a-z0-9]; accept
// the same alphabet with some length slack. Anything that passes this is safe
// to interpolate into URLs and HTML attributes without further escaping.
export const SHARE_ID_RE = /^[a-z0-9]{4,20}$/;

export const SITE_URL = 'https://commonplace.pro';

// Fetch a shared collection row. Returns { status: 'ok', data } |
// { status: 'not_found' } | { status: 'expired' }; throws on database errors.
// Expired rows are deleted (fire and forget) so they don't linger.
export async function loadShare(supabase, id) {
  const { data, error } = await supabase
    .from('shared_collections')
    .select('quotes, title, created_at, expires_at')
    .eq('id', id)
    .maybeSingle();

  if (error) throw error;
  if (!data) return { status: 'not_found' };

  if (data.expires_at && new Date(data.expires_at) < new Date()) {
    supabase.from('shared_collections').delete().eq('id', id).catch(() => {});
    return { status: 'expired' };
  }
  return { status: 'ok', data };
}

// Stored quotes are either the compact [text, source, category, fav] tuples
// the client posts, or (older rows) full quote objects.
export function readSharedQuote(q) {
  if (Array.isArray(q)) {
    const [text, source, category] = q;
    return { text: String(text || ''), source: String(source || ''), category: String(category || '') };
  }
  if (q && typeof q === 'object') {
    return { text: String(q.text || ''), source: String(q.source || ''), category: String(q.category || '') };
  }
  return null;
}

// The quote a share card and description lead with: the first favorite if
// there is one, else the first quote with any text.
export function pickFeaturedQuote(quotes) {
  if (!Array.isArray(quotes)) return null;
  const fav = quotes.find(q => (Array.isArray(q) ? q[3] === 1 : q?.favorite) && readSharedQuote(q)?.text);
  const pick = fav || quotes.find(q => readSharedQuote(q)?.text);
  return pick ? readSharedQuote(pick) : null;
}
